### ISSUE TITLE
v2-webhook throws an error

### ISSUE THREAD

**Issue by kamieniarz** [5310/discord-bot-castform#11]
I just switched to this new branch but after running it I have this error:

```
TypeError: JSONDB is not a constructor
    at /home/user/discord-bot-castform/index.js:46:20
    at exports.run (/home/user/discord-bot-castform/utils.js:1:20)
    at Object.<anonymous> (/home/user/discord-bot-castform/index.js:42:1)
    at Module._compile (internal/modules/cjs/loader.js:1118:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1138:10)
    at Module.load (internal/modules/cjs/loader.js:982:32)
    at Function.Module._load (internal/modules/cjs/loader.js:875:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:32:23)
    at Module._compile (internal/modules/cjs/loader.js:1118:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1138:10)
```

**Comment by 5310** [comment]
Oh, strange. I thought I'd already committed this change. Will check.

**Comment by 5310** [comment]
@kamieniarz I just freshly cloned the repo (`v2-webhook` is now the default branch); did an `npm i && npm start` and it works fine over here. 

Could you tell me what you did to get the error? Maybe check if your local copy of `index.js` has this line: https://github.com/5310/discord-bot-castform/blob/5912df701d6cd88a948c2692559aa5d64726f37e/index.js#L28

**Comment by kamieniarz** [comment]
Ok I managed to fix it somehow. Thanks 👌

**Comment by kamieniarz** [comment]
BTW could multiple webhooks be supported? In case I'd like to send 1 city to 2 different servers

**Comment by 5310** [comment]
It already is. The [webhooks property in `config.json`](https://github.com/5310/discord-bot-castform/blob/v2-webhook/template.config.json#L9-L14) is a list. Each location can have any number of different hooks. 

(Well, I say any number, I'm sure at some point Discord will throttle things because they're terrified for being DDoSed for some reason:)
