### ISSUE TITLE
unexpected token ? ajstewart

### ISSUE THREAD

**Issue by nileplumb** [5310/discord-bot-castform#18]
Throws an error after npm start with a clean clone and config on webhook branch

```
//model-ajstewart.js:172
  const weather = weatherMap[label] ?? { dominant: 'unknown', superficial: {}, windyable: false }
                                     ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:931:16)
    at Module._compile (internal/modules/cjs/loader.js:979:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/index.js:35:22)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
```

**Comment by 5310** [comment]
That's the new Nullish Coalescing operator. You will have to update to Node 14 or higher.

**Comment by nileplumb** [comment]
Right Ok, i vaguely remember one of my projects having problems on v15 so i downgraded to 12 and it's been smooth since.

The readme only mentions Node 10 so thought I'd be ok, perhaps update that?

**Comment by 5310** [comment]
Oh, I totally missed that! 

Will fix. I do remember fixing it on the `package.json` but I guess that properly is superficial outside of some hosting platforms.
