### ISSUE TITLE
Crashes when I try to add to channel.

### ISSUE THREAD

**Issue by Cynocephaly** [5310/discord-bot-castform#3]
When I try and add a channel to this bot I get the following message. Do you have a fix?

```
/root/discord-bot-castform/bot.js:18
    const setChannel = message.content.match(/<@!?[0-9]*> (?<command>setChannel) <#(?<channel>[0-9]*)>/)
                                       ^

SyntaxError: Invalid regular expression: /<@!?[0-9]*> (?<command>setChannel) <#(?<channel>[0-9]*)>/: Invalid group
    at Client.client.on.message (/root/discord-bot-castform/bot.js:18:40)
    at emitOne (events.js:116:13)
    at Client.emit (events.js:211:7)
    at MessageCreateHandler.handle (/root/discord-bot-castform/node_modules/.registry.npmjs.org/discord.js/11.4.2/node_modules/discord.js/src/client/websocket/packets/handlers/MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (/root/discord-bot-castform/node_modules/.registry.npmjs.org/discord.js/11.4.2/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:103:65)
    at WebSocketConnection.onPacket (/root/discord-bot-castform/node_modules/.registry.npmjs.org/discord.js/11.4.2/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:333:35)
    at WebSocketConnection.onMessage (/root/discord-bot-castform/node_modules/.registry.npmjs.org/discord.js/11.4.2/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:296:17)
    at WebSocket.onMessage (/root/discord-bot-castform/node_modules/.registry.npmjs.org/ws/4.1.0/node_modules/ws/lib/event-target.js:120:16)
    at emitOne (events.js:116:13)
    at WebSocket.emit (events.js:211:7)
```

**Comment by ajstewart** [comment]
If I remember I also encountered this, but realised I was running on an old npm. Switched to the latest I had installed (node v11.6.0, npm 6.5.0) re-installed and I got it running. (edit: at least I think that was the solution I found)

Though there is probably a fix that can be done to make it compatible.

**Comment by Cynocephaly** [comment]
I manually updated node to version 11 using [this ](https://github.com/nodesource/distributions/blob/master/README.md#installation-instructions)and it now works.

**Comment by ajstewart** [comment]
Great - node version manager (nvm - https://github.com/creationix/nvm) I find is pretty good for getting your versions under control.

@5310 do you know why this is is not backwards compatible?

**Comment by 5310** [comment]
I've been using ES2015+ features pretty liberally throughout the project so there'll be plenty of cases where it won't be backwards compatible with older Node versions :smile_cat: 

Thanks for the heads-up, I'm going to add this to the readme.
